TinkoffCreditSystems/stapp

- docs/modules/formBase.md
- src/modules/formBase/reducers.spec.ts
- src/modules/formBase/reducers.ts
- src/modules/validate/helpers.ts
- src/modules/validate/validate.spec.ts
formBase: don't reset error on setValue, validate: always return setError
> refactor formBase and validate modules

- packages/stapp/src/core/createEffect/createEffect.h.ts
- packages/stapp/src/core/createEffect/createEffect.ts
> feat(core): allow to provide error type to effectCreator

- .travis.yml
- packages/stapp-persist/package-lock.json
- packages/stapp-persist/package.json
- packages/stapp-react/package-lock.json
- packages/stapp-react/package.json
- packages/stapp-react/src/createConsumer/createConsumer.ts
- packages/stapp-rxjs/package-lock.json
- packages/stapp-rxjs/package.json
- packages/stapp-rxjs/src/combineEpics/combineEpics.ts
- packages/stapp-rxjs/src/index.ts
- packages/stapp-validate/package-lock.json
- packages/stapp-validate/package.json
- packages/stapp-validate/src/validate.h.ts
- packages/stapp-validate/src/validate.spec.ts
- packages/stapp-validate/src/validate.ts
- packages/stapp/package-lock.json
- packages/stapp/package.json
> feat(validate): refactor validate module, allow dynamic rules

- packages/stapp-formbase/src/events.ts
- packages/stapp-formbase/src/formBase.spec.ts
- packages/stapp-formbase/src/index.ts
- packages/stapp-formbase/src/reducers.ts
- packages/stapp-formbase/src/selectors.ts
> feat(formbase): add clearFields eventCreator

- package.json
- packages/template/.babelrc
- packages/template/.npmignore
- packages/template/LICENSE
- packages/template/README-TEMPLATE.md
- packages/template/README.md
- packages/template/jest.config.json
- packages/template/package-lock.json
- packages/template/package.json
- packages/template/src/index.spec.ts
- packages/template/src/index.ts
- packages/template/tsconfig.json
- packages/template/tslint.json
> feat(template): add package template

- packages/stapp-react/src/createConsumer/createConsumer.ts
> fix(react): fix map usage in Consumer

- packages/stapp/src/stapp.ts
> feat(core): export initDone event

- .size-limit.js
> fix(select): add stapp-select to .size-limit

- docs/modules/formbase.md
- packages/stapp-formbase/src/index.ts
> feat(formbase): export pickFields event from formbase index

- docs/guides/ssr.md
- packages/stapp/src/core/createApp/createApp.h.ts
- packages/stapp/src/core/createApp/createApp.spec.ts
- packages/stapp/src/core/createApp/getReadyPromise.ts
> feat(core): add condition method to WaitFor interface

- docs/guides/react.md
- docs/guides/ssr.md
- docs/modules/select.md
- package.json
- packages/stapp-react/src/context/context.spec.tsx
- packages/stapp-react/src/context/context.ts
> feat(react): add context-based version of consume, update docs

- docs/core/createReducer.md
- docs/core/epics.md
> docs(core): document select and selectArray

- docs/guides/interop.md
- packages/stapp-formbase/src/formBase.spec.ts
- packages/stapp-formbase/src/formBase.ts
- packages/stapp-persist/src/persist.ts
- packages/stapp-rxjs/src/combineEpics/combineEpics.ts
- packages/stapp-rxjs/src/index.ts
- packages/stapp-rxjs/src/observableConfig.ts
- packages/stapp-select/src/select.ts
- packages/stapp-validate/src/validate.ts
- packages/stapp/src/core/createApp/createApp.h.ts
- packages/stapp/src/core/createApp/createApp.spec.ts
- packages/stapp/src/core/createApp/createApp.ts
- packages/stapp/src/core/createApp/setObservableConfig.ts
- packages/stapp/src/stapp.ts
> Allow setting global observable config

- docs/modules/formbase.md
- packages/stapp-formbase/src/events.ts
- packages/stapp-formbase/src/formBase.h.ts
- packages/stapp-formbase/src/formBase.ts
> feat(formbase): expose formBase events to the API

- packages/stapp-formbase/src/formBase.spec.ts
- packages/stapp-formbase/src/selectors.ts
- packages/stapp-validate/src/selectors.ts
- packages/stapp-validate/src/validate.spec.ts
> Check selectors for safety

- packages/stapp-react/src/binded/createConsumer.spec.tsx
- packages/stapp-react/src/binded/createConsumer.ts
- packages/stapp-react/src/context/Consumer.ts
> fix(react): temporary fix for #109

- packages/stapp-validate/src/index.ts
> feat(validate): export revalidate event from index

- packages/stapp/src/core/createApp/createApp.ts
- packages/stapp/src/core/createEvent/createEvent.ts
- packages/stapp/src/helpers/uniqueId/uniqify.ts
- packages/stapp/src/helpers/uniqueId/uniqueId.spec.ts
> feat(core): add unique number only to non-unique identifiers

- packages/stapp-formbase/src/events.ts
- packages/stapp-formbase/src/formBase.h.ts
- packages/stapp-formbase/src/formBase.spec.ts
- packages/stapp-formbase/src/formBase.ts
- packages/stapp-formbase/src/index.ts
- packages/stapp-formbase/src/reducers.ts
- packages/stapp-formbase/src/selectors.ts
> feat(formbase): add meta reducer and setMeta event to formbase

- packages/stapp/src/core/createApp/createApp.h.ts
> fix(core): fix Dispatch typings

- package.json
> chore(root): run tests before push

- packages/stapp-react/src/createComponents/createForm.spec.tsx
- packages/stapp-react/src/createComponents/createForm.ts
- packages/stapp-react/src/helpers/simpleMemoize.spec.ts
- packages/stapp-react/src/helpers/simpleMemoize.ts
> fix(react): call preventDefault in Form callbacks
